# Generated by Django 6.0.2 on 2026-04-14 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique class code', max_length=100, unique=True)),
                ('name', models.CharField(help_text='Class name', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Class description', null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', help_text='Class status', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['code'], name='academics_a_code_9cc379_idx'), models.Index(fields=['status'], name='academics_a_status_87370f_idx')],
            },
        ),
        migrations.CreateModel(
            name='AcademicProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique program code (e.g., AP-0000001)', max_length=100, unique=True)),
                ('name', models.CharField(help_text='Program name', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Program description', null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', help_text='Program status', max_length=50)),
                ('program_type', models.CharField(blank=True, help_text='Type of program', max_length=100, null=True)),
                ('program_fee', models.DecimalField(blank=True, decimal_places=2, help_text='Program fee amount', max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['code'], name='academics_a_code_86c890_idx'), models.Index(fields=['status'], name='academics_a_status_cb21c1_idx')],
            },
        ),
        migrations.CreateModel(
            name='AcademicSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique section code', max_length=100, unique=True)),
                ('name', models.CharField(help_text='Section name', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Section description', null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', help_text='Section status', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['code'], name='academics_a_code_4b40f1_idx'), models.Index(fields=['status'], name='academics_a_status_e3c4a8_idx')],
            },
        ),
        migrations.CreateModel(
            name='AcademicSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique subject code', max_length=100, unique=True)),
                ('name', models.CharField(help_text='Subject name', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Subject description', null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', help_text='Subject status', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['code'], name='academics_a_code_6b4136_idx'), models.Index(fields=['status'], name='academics_a_status_453095_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProgramType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique program type code', max_length=100, unique=True)),
                ('name', models.CharField(help_text='Program type name', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Program type description', null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', help_text='Program type status', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['code'], name='academics_p_code_93c4de_idx'), models.Index(fields=['status'], name='academics_p_status_d9091f_idx')],
            },
        ),
    ]
