# Generated by Django 6.0.2 on 2026-04-20 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssetLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique asset location code (e.g., AL-0001)', max_length=100, unique=True)),
                ('name', models.CharField(help_text='Asset location name', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Asset location description', null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', help_text='Location status', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['code'], name='assets_asse_code_97e993_idx'), models.Index(fields=['status'], name='assets_asse_status_07449c_idx')],
            },
        ),
        migrations.CreateModel(
            name='AssetStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique asset status code (e.g., AS-0001)', max_length=100, unique=True)),
                ('name', models.CharField(help_text='Asset status name', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Asset status description', null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', help_text='Status record status', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Asset Statuses',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['code'], name='assets_asse_code_6d6b7a_idx'), models.Index(fields=['status'], name='assets_asse_status_527b96_idx')],
            },
        ),
        migrations.CreateModel(
            name='AssetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique asset type code (e.g., AT-0001)', max_length=100, unique=True)),
                ('type_name', models.CharField(help_text='Asset type name', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Asset type description', null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', help_text='Asset type status', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['code'], name='assets_asse_code_2517cc_idx'), models.Index(fields=['status'], name='assets_asse_status_ce15b4_idx')],
            },
        ),
        migrations.CreateModel(
            name='AssetSubType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique asset sub type code (e.g., AST-0001)', max_length=100, unique=True)),
                ('sub_type_name', models.CharField(help_text='Asset sub type name', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Asset sub type description', null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', help_text='Asset sub type status', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset_type', models.ForeignKey(help_text='Parent asset type', on_delete=django.db.models.deletion.PROTECT, related_name='subtypes', to='assets.assettype')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['code'], name='assets_asse_code_9a7423_idx'), models.Index(fields=['status'], name='assets_asse_status_dfeb78_idx')],
            },
        ),
    ]
