# Generated by Django 6.0.2 on 2026-04-19 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique account group code (e.g., AG-0001)', max_length=100, unique=True)),
                ('name', models.CharField(help_text='Account group name', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Account group description', null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', help_text='Account group status', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['code'], name='accounts_ac_code_f5b137_idx'), models.Index(fields=['status'], name='accounts_ac_status_31246b_idx')],
            },
        ),
        migrations.CreateModel(
            name='AccountNature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique account nature code (e.g., AN-0001)', max_length=100, unique=True)),
                ('name', models.CharField(help_text='Account nature name', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Account nature description', null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', help_text='Account nature status', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['code'], name='accounts_ac_code_2d7019_idx'), models.Index(fields=['status'], name='accounts_ac_status_b2bdb9_idx')],
            },
        ),
        migrations.CreateModel(
            name='CashBankVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField(help_text='Date of the voucher')),
                ('voucher_no', models.CharField(help_text='Unique voucher number', max_length=100, unique=True)),
                ('document_no', models.CharField(help_text='Unique document number', max_length=100, unique=True)),
                ('voucher_type', models.CharField(choices=[('CASH_PAYMENT', 'Cash Payment'), ('CASH_RECEIPT', 'Cash Receipt'), ('BANK_PAYMENT', 'Bank Payment'), ('BANK_RECEIPT', 'Bank Receipt')], help_text='Type of cash/bank voucher', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total transaction amount', max_digits=15)),
                ('bank', models.CharField(blank=True, help_text='Bank name (for bank vouchers)', max_length=100, null=True)),
                ('branch', models.CharField(blank=True, help_text='Branch name (for bank vouchers)', max_length=100, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', help_text='Voucher status', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['voucher_no'], name='accounts_ca_voucher_b368e5_idx'), models.Index(fields=['document_no'], name='accounts_ca_documen_8ed875_idx'), models.Index(fields=['voucher_type'], name='accounts_ca_voucher_3739e4_idx'), models.Index(fields=['status'], name='accounts_ca_status_96c400_idx')],
            },
        ),
        migrations.CreateModel(
            name='JournalVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField(help_text='Date of the journal voucher')),
                ('voucher_no', models.CharField(help_text='Unique voucher number', max_length=100, unique=True)),
                ('document_no', models.CharField(help_text='Unique document number', max_length=100, unique=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', help_text='Voucher status', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['voucher_no'], name='accounts_jo_voucher_32e405_idx'), models.Index(fields=['document_no'], name='accounts_jo_documen_a13b92_idx'), models.Index(fields=['status'], name='accounts_jo_status_ed85d8_idx')],
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_no', models.CharField(help_text='Reference document number', max_length=100)),
                ('booking_date', models.DateField(help_text='Date of the ledger entry')),
                ('total_debit', models.DecimalField(decimal_places=2, default=0, help_text='Total debit amount', max_digits=15)),
                ('total_credit', models.DecimalField(decimal_places=2, default=0, help_text='Total credit amount', max_digits=15)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', help_text='Ledger entry status', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['document_no'], name='accounts_le_documen_257e14_idx'), models.Index(fields=['booking_date'], name='accounts_le_booking_debf64_idx'), models.Index(fields=['status'], name='accounts_le_status_cb76ba_idx')],
            },
        ),
        migrations.CreateModel(
            name='Narration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('narration', models.TextField(help_text='Narration text')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', help_text='Narration status', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='accounts_na_status_c22c00_idx')],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_category', models.CharField(choices=[('VENDOR', 'Vendor Payment'), ('CUSTOMER', 'Customer Payment'), ('EMPLOYEE', 'Employee Payment')], help_text='Category of payment', max_length=20)),
                ('payment_type', models.CharField(choices=[('CASH', 'Cash'), ('CREDIT', 'Credit'), ('RETURN', 'Return'), ('BANK_TRANSFER', 'Bank Transfer'), ('ONLINE_BANK_TRANSFER', 'Online Bank Transfer'), ('CHEQUE', 'Cheque'), ('ADVANCE_PAYMENT', 'Advance Payment')], help_text='Type of payment method', max_length=30)),
                ('payment_date', models.DateField(help_text='Date of payment')),
                ('vendor', models.CharField(blank=True, help_text='Vendor name', max_length=200, null=True)),
                ('grn', models.CharField(blank=True, help_text='GRN reference', max_length=100, null=True)),
                ('customer', models.CharField(blank=True, help_text='Customer name', max_length=200, null=True)),
                ('bill', models.CharField(blank=True, help_text='Bill reference', max_length=100, null=True)),
                ('employee', models.CharField(blank=True, help_text='Employee name', max_length=200, null=True)),
                ('bank', models.CharField(blank=True, help_text='Bank name', max_length=100, null=True)),
                ('branch', models.CharField(blank=True, help_text='Branch name', max_length=100, null=True)),
                ('cheque_no', models.CharField(blank=True, help_text='Cheque number', max_length=100, null=True)),
                ('cheque_date', models.DateField(blank=True, help_text='Cheque date', null=True)),
                ('cheque_cash_date', models.DateField(blank=True, help_text='Cheque cashed date', null=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount', max_digits=15)),
                ('payment_note', models.TextField(blank=True, help_text='Additional payment notes', null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', help_text='Payment status', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['payment_category'], name='accounts_pa_payment_59e346_idx'), models.Index(fields=['payment_type'], name='accounts_pa_payment_c24ace_idx'), models.Index(fields=['payment_date'], name='accounts_pa_payment_fcb22f_idx'), models.Index(fields=['status'], name='accounts_pa_status_8957e4_idx')],
            },
        ),
        migrations.CreateModel(
            name='VoucherType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique voucher type code (e.g., VT-0001)', max_length=100, unique=True)),
                ('name', models.CharField(help_text='Voucher type name', max_length=200)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', help_text='Voucher type status', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['code'], name='accounts_vo_code_49ad0e_idx'), models.Index(fields=['status'], name='accounts_vo_status_ba2f5b_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChartOfAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique account code (e.g., COA-0001)', max_length=100, unique=True)),
                ('name', models.CharField(help_text='Account name', max_length=200)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, help_text='Opening balance of the account', max_digits=15)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', help_text='Account status', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_group', models.ForeignKey(help_text='Account group classification', on_delete=django.db.models.deletion.PROTECT, to='accounts.accountgroup')),
                ('account_nature', models.ForeignKey(help_text='Type of account nature', on_delete=django.db.models.deletion.PROTECT, to='accounts.accountnature')),
                ('parent_account', models.ForeignKey(blank=True, help_text='Parent account for hierarchy', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='accounts.chartofaccount')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['code'], name='accounts_ch_code_16562a_idx'), models.Index(fields=['status'], name='accounts_ch_status_33874d_idx')],
            },
        ),
    ]
